# MaxViT model default config 

  # dim_conv_stem: dimension of the convolutional stem, would default to dimension of first layer if not specified
  # dim: dimension of first layer, doubles every layer
  # dim_head: dimension of attention heads, kept at 32 in paper
  # depth: number of MaxViT blocks per stage, which consists of MBConv, block-like attention, grid-like attention
  # window_size: window size for block and grids
  # mbconv_expansion_rate: expansion rate of MBConv
  # mbconv_shrinkage_rate: shrinkage rate of squeeze-excitation in MBConv

MaxViT-S:
  num_classes: 1000
  dim_conv_stem: 64
  dim: 96               
  dim_head: 32                 
  depth: [2, 2, 5, 2]        
  window_size: 7               
  mbconv_expansion_rate: 4    
  mbconv_shrinkage_rate: 0.25    
  dropout: 0.1                    
MaxViT-L:
  num_classes: 1000
  dim_conv_stem: 128
  dim: 128               
  dim_head: 32                 
  depth: [2, 6, 14, 2]        
  window_size: 7            
  mbconv_expansion_rate: 4
  mbconv_shrinkage_rate: 0.25
  dropout: 0.1  