# Traing settings (colab env)

# path
dataset_path: rgb_ds
model_path: model_out/model.pt

# dataset:
test_size: 0.2
val_size: 0.2
seed: 39

# train:
batch_size: 16
epochs: 20
device: cuda

# optimizer:
lr: 3.0e-5
gamma: 0.7

